### ISSUE TITLE
hexo-next问题

### ISSUE THREAD

**Issue by maskleo** [maskleo/maskleo.github.io#23]
I found a sporadic problem.When I exec `hexo g` or Visit `http://localhost:4000` Will be wrong.
```
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\blog\masque-fate.github.io\themes\next\layout\_scripts\schemes\.swig'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.ret.load (D:\blog\masque-fate.github.io\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at exports.Swig.compileFile (D:\blog\masque-fate.github.io\node_modules\swig\lib\swig.js:695:31)
    at Object.eval [as tpl] (eval at precompile (D:\blog\masque-fate.github.io\node_modules\swig\lib\swig.js:498:13), <anonymous>:433:18)
    at compiled (D:\blog\masque-fate.github.io\node_modules\swig\lib\swig.js:619:18)
    at Theme._View.View._compiled (D:\blog\masque-fate.github.io\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\blog\masque-fate.github.io\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\masque-fate.github.io\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (D:\blog\masque-fate.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\masque-fate.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\masque-fate.github.io\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:443:10)
    at resume_ (_stream_readable.js:823:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
When I close the browser and related software, or multiple times exec `hexo g` And normal operation.
I checked my configuration several times and found that it did happen occasionally without any changes.
I use the `win10` system, using the administrator privileges to execute the command.
This error is only found in this update. I deleted the original node_modules folder and executed `npm install`
Other abnormalities:
```
Error: D:/blog/masque-fate.github.io/themes/next/source/css/_common/components/highlight/highlight.styl:79:30
   75|
   76|   .gutter pre {
   77|     padding-left: 10px
   78|     padding-right: 10px
   79|     color: $highlight-gutter.color
------------------------------------^
   80|     text-align: right
   81|     background-color: $highlight-gutter.bg-color
   82|   }

$highlight-gutter has no property .color
    at ".gutter pre " (D:/blog/masque-fate.github.io/themes/next/source/css/_common/components/highlight/highlight.styl:75:4)
    at ".highlight " (D:/blog/masque-fate.github.io/themes/next/source/css/_common/components/highlight/highlight.styl:39:2)

    at Evaluator.visitMember (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:351:11)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitGroup (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:261:22)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitGroup (D:\blog\masque-fate.github.io\node_modules\stylus\lib\visitor\evaluator.js:261:22)
```

**Comment by maskleo** [comment]
update `_config.yml`
